### ISSUE TITLE
Шулер

### ISSUE THREAD

**Issue by StriderAJR** [Filsnake/CppLabs#1]
Ага.
```
	int x = 2; //число строк
	int y = 2; //число столбцов 
```
Да вот прям щас. Ага. Нефиг читерить. Размер матрицы вводит пользователь с экрана. Максимум можете сделать проверку на четность.

**Comment by Filsnake** [comment]
Так, ну я вроде исправил. Просто в задании сказано было число строк и столбцов, поэтому я их там и ввел 
![qfkq-pcaevq](https://user-images.githubusercontent.com/31774389/31659792-ef14ea6e-b33d-11e7-9d57-cd01361a3b62.jpg)

**Comment by StriderAJR** [comment]
@Filsnake А нужно было спросить об этом пользователя. На будущее имейте в виду.
